#!/bin/bash

# generate_redirects.sh will place a set of 302 redirects into static/_redirects
# for Netlify to use. Before running it, make sure that your local modules
# dependencies are up to date. This involves performing go get @latest for all
# of the modules listed below. Do not merge the go.mod and go.sum changes that
# result; netlify appears to have issues when this is done.

SUITE=$(cat <<END
	gonum.org/v1/gonum/...
	gonum.org/v1/plot/...
	gonum.org/v1/netlib/...
	gonum.org/v1/hdf5/...
	gonum.org/v1/exp/...
END
)

(
	echo '# Generated by generate_directs.sh; DO NOT EDIT.'	
	echo '# Redirects to get to docs to a more helpful location.'	

	go list -f "{{.ImportPath}}/* https://pkg.go.dev/{{.ImportPath}}/ 302" $SUITE \
	| sed -r 's/^gonum\.org//g' \
	| awk '{ print length(), $0 | "sort -k1,1rn -k2" }' \
	| cut -d ' ' -f 2-

	go list -f "{{.Path}} https://pkg.go.dev/{{.Path}}/ 302" -m $SUITE \
	| sed -r 's/^gonum\.org//g'
)> static/_redirects
